### ISSUE TITLE
[ WARHING!! ] STOLE TOKEN 

### ISSUE THREAD

**Issue by BeamKunGzMARK** [DwifteJB/dwifte.py#8]
WHY HAVE DISCORD.WEBHOOK???

**Comment by DwifteJB** [comment]
Uhh? I was using it for development, logging errors, I'll get rid of it now.

**Comment by DwifteJB** [comment]
This was planned to be closed source and it would say 'BOTNAME is online' the code is open source anyway, so you can check the code now.

**Comment by CrafterPika** [comment]
This does not steal your token. 
The whole thing is open source check yourself the code.

**Comment by DwifteJB** [comment]
this still makes me laugh
