### ISSUE TITLE
DM Command

### ISSUE THREAD

**Issue by Beta692** [DwifteJB/dwifte.py#9]
After the most recent update the -mall (Message all) has stopped working. The picture attached shows what the terminal say when running the command.
![image](https://user-images.githubusercontent.com/73276908/96840539-d2450f80-1407-11eb-99f2-bce0cb266937.png)

**Comment by DwifteJB** [comment]
I'll test it and find the issue, sorry!

**Comment by Beta692** [comment]
Sounds good man, on top of it I dig that! Also idk if this was just a user issue cause I make mistakes but when I updated and tried to run it said there is no module 'wget' which wasn't in requirements.txt so I just downloaded separately and it ran fine!

**Comment by DwifteJB** [comment]
Sorry for the late response, found that bug and added it into requirements, I'm testing the mall rn

**Comment by DwifteJB** [comment]
Seems to be working for me, it could be because the user has dms off or they have blocked you. I'll test again, quickly.

**Comment by Beta692** [comment]
It worked fine in the server I tested with on a diff acc and then I switched tokens and it stopped working maybe that could be the issue?

**Comment by DwifteJB** [comment]
Working for me. Any other issues and make another issue. If this keeps happening, try it on an alt.
